postgresql:
  auth:
    username: admin
    password: supersecret
    database: pedidos
  primary:
    persistence:
      enabled: true
      size: 1Gi
backend:
  image:
    repository: rougev/pedido-backend
    tag: "1.0.1"
  replicas: 2
  db:
    host: pedido-app-postgresql.my-tech.svc.cluster.local
    name: pedidos
    port: 5432
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"