apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: {{ .Values.backend.db.host }}
  DB_NAME: {{ .Values.backend.db.name }}
  DB_PORT: "{{ .Values.backend.db.port }}"
