apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JoseSantacruz12000/Prueba-Trabajo-K8s.git   
    targetRevision: HEAD                                 
    path: charts/pedido-app                              
    helm:
      valueFiles:
        - values.yaml                                    
  destination:
    server: https://kubernetes.default.svc
    namespace: my-tech                                   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
